version: "3.8"
services:
  db: 
    platform: linux/amd64
    container_name: cms_db
    restart: always
    env_file:
      - .env
    image: mysql:5.7.22
    ports:
      - '3306:3306'
    networks:
      - dev
    volumes:
      - cms-template-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:  mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 5

  strapi:
    container_name: cms
    restart: always
    env_file:
      - .env
      - ./cms/.env
    build:
      target: dev
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    networks:
      - dev
    volumes:
      - ./cms:/cms:delegated
      - /cms/node_modules
    depends_on:
      db:
        condition: service_healthy

  front:
    container_name: front
    restart: always
    env_file:
      - .env
    build:
      target: dev
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - dev
    volumes:
      - ./front:/front:delegated
      - /front/node_modules

volumes:
    cms-template-data:

networks:
  dev:
    driver: bridge
